students = [    
    {    
    "id": 1,    
    "name": "Divyansh Agrawal",        
    "country": "India",        
    "picture": "agrawal.jpg",   
    "country_flag": "India.png",     
    "title": "Mental health stigma in India causes delays in intervention and treatment",        
    "subtitle": "Some multigenerational families provide guidance for youth while others pass down misconceptions about mental health.",        
    "article_file": "static/articles/Divyansh_Agrawal/Divyansh_Agrawal.txt",        
    "quote": "“As you talk to more people, you get aware, and then you can decide what\'s best for you,” Argawal said.",
    "author": "Winter Hawk",
    "audio_file": "IndiaDivyansh.mp3"    
    },    
    {
    "id": 2,
    "name": "Sophia Andersen",        
    "country": "Denmark",        
    "picture": "andersen.png", 
    "country_flag": "Denmark.png",       
    "title": "TITLE HERE",        
    "subtitle": "SUBTITLE HERE",        
    "article_file": "static/articles/Sophia Andersen/Sophia_Andersen.txt",        
    "quote": "“I'm still trying to figure out how to live with ADHD, but I feel like the depression is not really that big a deal anymore,” Katharina Andersen said. “I don't go into those slumps anymore because I'm learning how to manage it beforehand.",
    "author": "AUTHOR",
    "audio_file": "DenmarkKatharina.mp3"     
    }, 
    {
    "id": 3,
    "name": "Luisa Barros-Checcucci",        
    "country": "Belgium",        
    "picture": "PICTURE HERE", 
    "country_flag": "Belgium.png",       
    "title": "Lack of trained mental health personnel in schools poses risks to student outlook",        
    "subtitle": "After moving to Maryland from Belgium, Luisa Barros-Checcucci struggled to find the same support she had in Belgium. ",        
    "article_file": "static/articles/Luisa Barros-Checcucci/Luisa_Barros-Checcucci.txt",        
    "quote": "“I was breaking down and he made me feel terrible,” Barros-Checcucci said. “He was just kind of like, 'okay, well what do you want me to do about it' type of thing.”",
    "author": "Winter Hawk",
    "audio_file": "BelgiumLua.mp3"     
    }, 
    {
    "id": 4,
    "name": "Ubaid Bakhtiar",        
    "country": "Pakistan",         
    "picture": "bakhtiar.png",  
    "country_flag": "Pakistan.png",      
    "title": "State corruption and family pressure stifle health progress of rural Pakistani communities",        
    "subtitle": "Political instability and underfunded health systems perpetuate cycles of violence and poor mental health in Pakistan.",        
    "article_file": "static/articles/Ubaid Bakhtiar/Ubaid_Bakhtiar.txt",   
    "quote": "“I dont have a friend from U.S.A,” Bakhtiar said. “People who are in U.S.A, they prefer to have friends with the people that are from U.S.A”",
    "author": "AUTHOR",
    "audio_file": "PakistanUbaid.mp3"     
    }, 
    {
    "id": 5,
    "name": "Seungji Rhee",        
    "country": "South Korea",        
    "picture": "rhee.png",      
    "country_flag": "South_Korea.png",  
    "title": "Students in South Korea begin to value self-care amid academic pressures",        
    "subtitle": "South Korean media and television are helping raise awareness of youth experiences with stress and anxiety.",        
    "article_file": "static/articles/Seungji Rhee/Seungji_Rhee.txt",   
    "quote": "QUOTE HERE",
    "author": "Winter Hawk",
    "audio_file": "KoreaRhee.mp3"     
    }, 
    {
    "id": 6,
    "name": "Herbert Obeng",        
    "country": "Ghana",        
    "picture": "PICTURE HERE",        
    "country_flag": "Ghana.png",
    "title": "TITLE HERE",        
    "subtitle": "SUBTITLE HERE",        
    "article_file": "static/articles/Herbert Obeng/Herbert_Obeng.txt",   
    "quote": "QUOTE HERE",
    "author": "Winter Hawk",
    "audio_file": "GhanaHerbert.mp3"     
    }, 
    {
    "id": 7,
    "name": "NAME",        
    "country": "Peru",        
    "picture": "PICTURE",       
    "country_flag": "Peru.png", 
    "title": "TITLE HERE",        
    "subtitle": "SUBTITLE HERE",        
    "article_file": "ARTICLE FILE",   
    "quote": "QUOTE HERE",
    "author": "AUTHOR",
    "audio_file": "AUDIO"     
    }, 
    {
    "id": 8,
    "name": "Lindia Gonzalez",        
    "country": "El Salvador",   
    "country_flag": "El_Salvador.png",     
    "picture": "NO PHOTO",        
    "title": "TITLE HERE",        
    "subtitle": "SUBTITLE HERE",        
    "article_file": "static/articles/Lindia Gonzalez/Lindia_Gonzalez.txt",   
    "quote": "QUOTE HERE",
    "author": "Winter Hawk",
    "audio_file": "AUDIO"     
    }
]